// <auto-generated />
using System;
using MedicalCertificate.Infrastructure.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedicalCertificate.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260512212714_minor_fixes")]
    partial class minor_fixes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MedicalCertificate.Domain.Entities.Certificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CertificateStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Clinic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FilePathId")
                        .HasColumnType("int");

                    b.Property<string>("ReviewerComment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int?>("StoredFileId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CertificateStatusId");

                    b.HasIndex("StatusId");

                    b.HasIndex("StoredFileId");

                    b.HasIndex("UserId");

                    b.ToTable("certificates", (string)null);
                });

            modelBuilder.Entity("MedicalCertificate.Domain.Entities.CertificateStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("certificatestatuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Status = "В обработке"
                        },
                        new
                        {
                            Id = 2,
                            Status = "Принято"
                        },
                        new
                        {
                            Id = 3,
                            Status = "Отклонено"
                        });
                });

            modelBuilder.Entity("MedicalCertificate.Domain.Entities.CertificateStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CertificateId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ChangedBy")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CertificateId");

                    b.HasIndex("ChangedBy");

                    b.HasIndex("StatusId");

                    b.ToTable("certificatestatushistories", (string)null);
                });

            modelBuilder.Entity("MedicalCertificate.Domain.Entities.Edu_EducationTypes", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("NoBDID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Edu_EducationTypes", (string)null);
                });

            modelBuilder.Entity("MedicalCertificate.Domain.Entities.Edu_EmployeePositions", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("EndedOn")
                        .HasColumnType("date");

                    b.Property<int?>("HrOrderId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsMainPosition")
                        .HasColumnType("bit");

                    b.Property<string>("LastUpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrgUnitID")
                        .HasColumnType("int");

                    b.Property<int>("PositionID")
                        .HasColumnType("int");

                    b.Property<double?>("Rate")
                        .HasColumnType("float");

                    b.Property<DateOnly>("StartedOn")
                        .HasColumnType("date");

                    b.HasKey("ID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("OrgUnitID");

                    b.HasIndex("PositionID");

                    b.ToTable("Edu_EmployeePositions", (string)null);
                });

            modelBuilder.Entity("MedicalCertificate.Domain.Entities.Edu_Employees", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<bool>("IsAdvisor")
                        .HasColumnType("bit");

                    b.Property<int?>("RoleGroupId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Edu_Employees", (string)null);
                });

            modelBuilder.Entity("MedicalCertificate.Domain.Entities.Edu_OrgUnitTypes", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Edu_OrgUnitTypes", (string)null);
                });

            modelBuilder.Entity("MedicalCertificate.Domain.Entities.Edu_OrgUnits", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentID")
                        .HasColumnType("int");

                    b.Property<string>("ShortTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ParentID");

                    b.HasIndex("TypeID");

                    b.ToTable("Edu_OrgUnits", (string)null);
                });

            modelBuilder.Entity("MedicalCertificate.Domain.Entities.Edu_Positions", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("CategoryID")
                        .HasColumnType("int");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Labs")
                        .HasColumnType("int");

                    b.Property<int>("Lectures")
                        .HasColumnType("int");

                    b.Property<int>("Practices")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Edu_Positions", (string)null);
                });

            modelBuilder.Entity("MedicalCertificate.Domain.Entities.Edu_Students", b =>
                {
                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("AcademicStatusEndsOn")
                        .HasColumnType("date");

                    b.Property<int?>("AcademicStatusID")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("AcademicStatusStartsOn")
                        .HasColumnType("date");

                    b.Property<int?>("AdvisorID")
                        .HasColumnType("int");

                    b.Property<bool>("AltynBelgi")
                        .HasColumnType("bit");

                    b.Property<int?>("CategoryID")
                        .HasColumnType("int");

                    b.Property<double?>("EctsGPA")
                        .HasColumnType("float");

                    b.Property<double?>("EctsGPA_Y")
                        .HasColumnType("float");

                    b.Property<int?>("EducationDurationID")
                        .HasColumnType("int");

                    b.Property<int?>("EducationPaymentTypeID")
                        .HasColumnType("int");

                    b.Property<int?>("EducationTypeID")
                        .HasColumnType("int");

                    b.Property<int?>("EnrollmentTypeId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("EntryDate")
                        .HasColumnType("date");

                    b.Property<int?>("FundingID")
                        .HasColumnType("int");

                    b.Property<double?>("GPA")
                        .HasColumnType("float");

                    b.Property<double?>("GPA_Y")
                        .HasColumnType("float");

                    b.Property<DateTime?>("GraduatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GrantTypeID")
                        .HasColumnType("int");

                    b.Property<int?>("HosterPrivelegeID")
                        .HasColumnType("int");

                    b.Property<bool?>("IsKNB")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPersonalDataComplete")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsScholarship")
                        .HasColumnType("bit");

                    b.Property<string>("LastUpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MinorSpecialityID")
                        .HasColumnType("int");

                    b.Property<bool>("NeedsDorm")
                        .HasColumnType("bit");

                    b.Property<int?>("RupID")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ScholarshipDateEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ScholarshipDateStart")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ScholarshipOrderDate")
                        .HasColumnType("date");

                    b.Property<string>("ScholarshipOrderNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ScholarshipTypeID")
                        .HasColumnType("int");

                    b.Property<int?>("SpecialityID")
                        .HasColumnType("int");

                    b.Property<int?>("StatusID")
                        .HasColumnType("int");

                    b.Property<int?>("StudyLanguageID")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("StudentID");

                    b.HasIndex("SpecialityID");

                    b.ToTable("Edu_Students", (string)null);
                });

            modelBuilder.Entity("MedicalCertificate.Domain.Entities.Edu_Users", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("CitizenCategoryID")
                        .HasColumnType("int");

                    b.Property<int?>("CitizenshipCountryID")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DOB")
                        .HasColumnType("date");

                    b.Property<int?>("ESUVOID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ExtraFileContainerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FileContainerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Hero_Person_ID")
                        .HasColumnType("int");

                    b.Property<string>("HomePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsReadTeamsNotif")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Male")
                        .HasColumnType("bit");

                    b.Property<int?>("MaritalStatusID")
                        .HasColumnType("int");

                    b.Property<int?>("MessengerTypeID")
                        .HasColumnType("int");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobilePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobilePushID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NationalityID")
                        .HasColumnType("int");

                    b.Property<string>("PersonalEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PhotoFileData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PhotoFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Resident")
                        .HasColumnType("bit");

                    b.Property<int?>("oldId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Edu_Users", (string)null);
                });

            modelBuilder.Entity("MedicalCertificate.Domain.Entities.Operation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("OperationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("System")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Operation");
                });

            modelBuilder.Entity("MedicalCertificate.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Office Registrar"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Student"
                        });
                });

            modelBuilder.Entity("MedicalCertificate.Domain.Entities.RoleOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OperationId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OperationId");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleOperation");
                });

            modelBuilder.Entity("MedicalCertificate.Domain.Entities.StoredFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bucket")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("storedfiles", (string)null);
                });

            modelBuilder.Entity("MedicalCertificate.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EduUserId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EduUserId")
                        .IsUnique()
                        .HasFilter("[EduUserId] IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MedicalCertificate.Domain.Entities.Certificate", b =>
                {
                    b.HasOne("MedicalCertificate.Domain.Entities.CertificateStatus", null)
                        .WithMany("Certificates")
                        .HasForeignKey("CertificateStatusId");

                    b.HasOne("MedicalCertificate.Domain.Entities.CertificateStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedicalCertificate.Domain.Entities.StoredFile", null)
                        .WithMany("Certificates")
                        .HasForeignKey("StoredFileId");

                    b.HasOne("MedicalCertificate.Domain.Entities.Edu_Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MedicalCertificate.Domain.Entities.CertificateStatusHistory", b =>
                {
                    b.HasOne("MedicalCertificate.Domain.Entities.Certificate", "Certificate")
                        .WithMany("StatusHistories")
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicalCertificate.Domain.Entities.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicalCertificate.Domain.Entities.CertificateStatus", "CertificateStatus")
                        .WithMany("StatusHistories")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Certificate");

                    b.Navigation("CertificateStatus");

                    b.Navigation("ChangedByUser");
                });

            modelBuilder.Entity("MedicalCertificate.Domain.Entities.Edu_EmployeePositions", b =>
                {
                    b.HasOne("MedicalCertificate.Domain.Entities.Edu_Employees", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedicalCertificate.Domain.Entities.Edu_OrgUnits", "OrgUnit")
                        .WithMany()
                        .HasForeignKey("OrgUnitID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedicalCertificate.Domain.Entities.Edu_Positions", "Position")
                        .WithMany()
                        .HasForeignKey("PositionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("OrgUnit");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("MedicalCertificate.Domain.Entities.Edu_Employees", b =>
                {
                    b.HasOne("MedicalCertificate.Domain.Entities.Edu_Users", "User")
                        .WithOne("Employee")
                        .HasForeignKey("MedicalCertificate.Domain.Entities.Edu_Employees", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MedicalCertificate.Domain.Entities.Edu_OrgUnits", b =>
                {
                    b.HasOne("MedicalCertificate.Domain.Entities.Edu_OrgUnits", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MedicalCertificate.Domain.Entities.Edu_OrgUnitTypes", "Type")
                        .WithMany()
                        .HasForeignKey("TypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("MedicalCertificate.Domain.Entities.Edu_Students", b =>
                {
                    b.HasOne("MedicalCertificate.Domain.Entities.Edu_OrgUnits", "Speciality")
                        .WithMany()
                        .HasForeignKey("SpecialityID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MedicalCertificate.Domain.Entities.Edu_Users", "User")
                        .WithOne("Student")
                        .HasForeignKey("MedicalCertificate.Domain.Entities.Edu_Students", "StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Speciality");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MedicalCertificate.Domain.Entities.RoleOperation", b =>
                {
                    b.HasOne("MedicalCertificate.Domain.Entities.Operation", "Operation")
                        .WithMany("RoleOperations")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicalCertificate.Domain.Entities.Role", "Role")
                        .WithMany("RoleOperations")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MedicalCertificate.Domain.Entities.User", b =>
                {
                    b.HasOne("MedicalCertificate.Domain.Entities.Edu_Users", "EduUser")
                        .WithOne("User")
                        .HasForeignKey("MedicalCertificate.Domain.Entities.User", "EduUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MedicalCertificate.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EduUser");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MedicalCertificate.Domain.Entities.Certificate", b =>
                {
                    b.Navigation("StatusHistories");
                });

            modelBuilder.Entity("MedicalCertificate.Domain.Entities.CertificateStatus", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("StatusHistories");
                });

            modelBuilder.Entity("MedicalCertificate.Domain.Entities.Edu_OrgUnits", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("MedicalCertificate.Domain.Entities.Edu_Users", b =>
                {
                    b.Navigation("Employee");

                    b.Navigation("Student");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MedicalCertificate.Domain.Entities.Operation", b =>
                {
                    b.Navigation("RoleOperations");
                });

            modelBuilder.Entity("MedicalCertificate.Domain.Entities.Role", b =>
                {
                    b.Navigation("RoleOperations");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("MedicalCertificate.Domain.Entities.StoredFile", b =>
                {
                    b.Navigation("Certificates");
                });
#pragma warning restore 612, 618
        }
    }
}
